### PR TITLE
use completion api to custom-completion mode

### PR DESCRIPTION
**Pull request by karburator**
Some model are more effective in completion scenarios.
Allow to use custom model for text completion
- added completion setting category
- use completion API instead of chat if completion model is initialized

### CODE REVIEW

**Comment by jeffdapaz** [comment]
Hi @karburator, thanks for your collaboration!

When a have some time, I'll test your solution and do the review.

**Comment by jeffdapaz** [comment]
Hi @karburator.

I ran some tests with your implementation and also checked out the OpenAI documentation, and I don’t think using the Completions API is a good solution.

The first reason is that it no longer receives updates from OpenAI, which means it’s stuck on some outdated models that won’t be updated anymore.

Secondly, I tested your solution using the three available models for completions (davinci-002, babbage-002, and gpt-3.5-turbo-instruct), and the responses were pretty poor—most of the time the code returned didn’t make sense for what it was supposed to complete. I could try tweaking the parameters and the command sent to improve it, but I doubt I’d see much of a difference in the responses.

Thirdly, while it’s not crucial, it adds a bit more complexity to the extension's configurations, especially since there’s no real benefit from it.

If you have any tips for getting better responses, I could test it out again. In the meantime, I appreciate your help regardless.

**Comment by karburator** [comment]
Hi @jeffdapaz, thanks for your review.

I tried to set "Model Parameters" => "Max Tokens" = 1024.
Then I compared deepseek-coder-6.7b-base and llama-3.1-8B-instruct models.
Deepseek-coder worked faster and generated more relevant code completion in my cases.

I wish to use different models in chat and code completion scenarios, think it makes sense.
What do you think about to separate chat and code completion flows and use different models?
Should I try to implement this based on '/chat/completion' API?

**Comment by jeffdapaz** [comment]
Ok @karburator, now I get it. My tests were done using the OpenAI API, but in your case, other LLMs were used, which is why there's a difference in the results.

In this case, I think it's valid. I like the idea of the extension being customizable, so everyone can find the best results for themselves.

However, instead of making "Completion" available only for the "copilot" feature, I believe a better approach would be to make it available not just for the copilot but also for commands via the code editor.

So, instead of deciding whether to use Completion by checking if the "Custom Model" option is filled out, there could be a true/false option in the general section that would be something like "Use Completion for Commands." If set to true, it would use Completion for both commands and the copilot, and the Chat endpoint would only be for "Turbo Chat." Otherwise, everything would continue using Chat as it does today.

What do you think?

**Comment by jeffdapaz** [comment]
Hi @karburator,

I will approve your PR, but first I need fix a issue, the extension lost compatibility with the newly VS version (17.12.0).

Thanks!

**Review by jeffdapaz — APPROVED** [review]

**Pull request merged**
